In [1]:
from google.colab import files
uploaded = files.upload()

Saving a-blood-analysis-lab-protocol.pdf to a-blood-analysis-lab-protocol.pdf
Saving CSI-clinical-practice-guidelines-for-dyslipidemia-_240413_141815.pdf to CSI-clinical-practice-guidelines-for-dyslipidemia-_240413_141815.pdf
Saving Guidelines-Made-Simple-Tool-2018-Cholesterol.pdf to Guidelines-Made-Simple-Tool-2018-Cholesterol.pdf
Saving sterling-accuris-pathology-sample-report-unlocked.pdf to sterling-accuris-pathology-sample-report-unlocked.pdf
Saving Hospital_Sample_Blood_Report.pdf to Hospital_Sample_Blood_Report.pdf
Saving Sample_Consolidated_Blood_Report.pdf to Sample_Consolidated_Blood_Report.pdf
Saving CBC-test-report-format-example-sample-template-Drlogy-lab-report.pdf to CBC-test-report-format-example-sample-template-Drlogy-lab-report.pdf

In [2]:
!pip install pdfplumber

Collecting pdfplumber
  Downloading pdfplumber-0.11.8-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 2.2 MB/s eta 0:00:00
Collecting pdfminer.six==20251107 (from pdfplumber)
  Downloading pdfminer_six-20251107-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (11.3.0)
Collecting pypdfium2>=4.18.0 (from pdfplumber)
  Downloading pypdfium2-5.2.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.8/67.8 kB 5.0 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251107->pdfplumber) (3.4.4)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251107->pdfplumber) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six==20251107->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20251107->pdfplumber) (2.23)
Downloading pdfplumber-0.11.8-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 4.7 MB/s eta 0:00:00
Downloading pdfminer_six-20251107-py3-none-any.whl (5.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 46.7 MB/s eta 0:00:00
Downloading pypdfium2-5.2.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 93.8 MB/s eta 0:00:00
Installing collected packages: pypdfium2, pdfminer.six, pdfplumber
Successfully installed pdfminer.six-20251107 pdfplumber-0.11.8 pypdfium2-5.2.0

In [3]:
!pip install pdfplumber
!apt-get install -y tesseract-ocr
!pip install pytesseract pdf2image

Requirement already satisfied: pdfplumber in /usr/local/lib/python3.12/dist-packages (0.11.8)
Requirement already satisfied: pdfminer.six==20251107 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (20251107)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (11.3.0)
Requirement already satisfied: pypdfium2>=4.18.0 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (5.2.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251107->pdfplumber) (3.4.4)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251107->pdfplumber) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six==20251107->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20251107->pdfplumber) (2.23)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tesseract-ocr is already the newest version (4.1.1-2.1build1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Collecting pytesseract
  Downloading pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Collecting pdf2image
  Downloading pdf2image-1.17.0-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from pytesseract) (25.0)
Requirement already satisfied: Pillow>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from pytesseract) (11.3.0)
Downloading pytesseract-0.3.13-py3-none-any.whl (14 kB)
Downloading pdf2image-1.17.0-py3-none-any.whl (11 kB)
Installing collected packages: pytesseract, pdf2image
Successfully installed pdf2image-1.17.0 pytesseract-0.3.13

In [19]:
import os

files = os.listdir()
print(files)

['.config', 'validated_standardized_parameters.csv', 'CBC-test-report-format-example-sample-template-Drlogy-lab-report.pdf', 'combined_cleaned_text.txt', 'Hospital_Sample_Blood_Report.pdf', 'combined_raw_text.txt', 'milestone2_pattern_analysis.csv', 'Sample_Consolidated_Blood_Report.pdf', 'sterling-accuris-pathology-sample-report-unlocked.pdf', 'extracted_parameters.csv', 'Guidelines-Made-Simple-Tool-2018-Cholesterol.pdf', 'CSI-clinical-practice-guidelines-for-dyslipidemia-_240413_141815.pdf', 'a-blood-analysis-lab-protocol.pdf', 'sample_data']

In [20]:
import pdfplumber
import pytesseract
from pdf2image import convert_from_path

def extract_text_from_pdf(pdf_path):
    extracted = ""

    try:
        with pdfplumber.open(pdf_path) as pdf:
            print(f"\n Reading (text mode): {pdf_path}")
            for page_num, page in enumerate(pdf.pages, start=1):
                text = page.extract_text()

                if text and text.strip():
                    extracted += f"\n--- Page {page_num} (text) ---\n"
                    extracted += text + "\n"
                else:
                    print(f"   Page {page_num}: no text, using OCR...")
                    img = page.to_image(resolution=300).original
                    ocr_text = pytesseract.image_to_string(img)
                    extracted += f"\n--- Page {page_num} (ocr) ---\n"
                    extracted += ocr_text + "\n"

    except Exception as e:
        print(f"pdfplumber failed on {pdf_path}, using pure OCR. Error: {e}")
        pages = convert_from_path(pdf_path)
        for i, p in enumerate(pages, start=1):
            ocr_text = pytesseract.image_to_string(p)
            extracted += f"\n--- Page {i} (ocr only) ---\n"
            extracted += ocr_text + "\n"

    return extracted

In [21]:
import os

pdf_files = [f for f in os.listdir() if f.lower().endswith(".pdf")]
print("Found PDF files:", pdf_files)

all_text = ""

for pdf in pdf_files:
    print(f"Processing: {pdf}")
    pdf_text = extract_text_from_pdf(pdf)
    all_text += f"\n\n\n===== FILE: {pdf} =====\n\n"
    all_text += pdf_text

print("\n Finished extracting ")
print("Total characters extracted:", len(all_text))

Found PDF files: ['CBC-test-report-format-example-sample-template-Drlogy-lab-report.pdf', 'Hospital_Sample_Blood_Report.pdf', 'Sample_Consolidated_Blood_Report.pdf', 'sterling-accuris-pathology-sample-report-unlocked.pdf', 'Guidelines-Made-Simple-Tool-2018-Cholesterol.pdf', 'CSI-clinical-practice-guidelines-for-dyslipidemia-_240413_141815.pdf', 'a-blood-analysis-lab-protocol.pdf']
Processing: CBC-test-report-format-example-sample-template-Drlogy-lab-report.pdf

 Reading (text mode): CBC-test-report-format-example-sample-template-Drlogy-lab-report.pdf

WARNING:pdfminer.pdfinterp:Cannot set gray stroke color because /'P29' is an invalid float value
WARNING:pdfminer.pdfinterp:Cannot set gray non-stroke color because /'P29' is an invalid float value

Processing: Hospital_Sample_Blood_Report.pdf

 Reading (text mode): Hospital_Sample_Blood_Report.pdf
Processing: Sample_Consolidated_Blood_Report.pdf

 Reading (text mode): Sample_Consolidated_Blood_Report.pdf
Processing: sterling-accuris-pathology-sample-report-unlocked.pdf

 Reading (text mode): sterling-accuris-pathology-sample-report-unlocked.pdf
Processing: Guidelines-Made-Simple-Tool-2018-Cholesterol.pdf

 Reading (text mode): Guidelines-Made-Simple-Tool-2018-Cholesterol.pdf
Processing: CSI-clinical-practice-guidelines-for-dyslipidemia-_240413_141815.pdf

 Reading (text mode): CSI-clinical-practice-guidelines-for-dyslipidemia-_240413_141815.pdf
Processing: a-blood-analysis-lab-protocol.pdf

 Reading (text mode): a-blood-analysis-lab-protocol.pdf

 Finished extracting
Total characters extracted: 230917

In [22]:

print(all_text[:2000])

===== FILE: CBC-test-report-format-example-sample-template-Drlogy-lab-report.pdf =====


--- Page 1 (text) ---
DRLOGY PATHOLOGY LAB
0123456789 | 0912345678
drlogypathlab@drlogy.com
Accurate | Caring | Instant
105 -108, SMART VISION COMPLEX, HEALTHCARE ROAD, OPPOSITE HEALTHCARE COMPLEX. MUMBAI - 689578
www.drlogy.com
Yash M. Patel Sample Collected At:
Age : 21 Years 125, Shivam Bungalow, S G Road,
Registered on: 02:31 PM 02 Dec, 2X
Mumbai
Sex : Male
Collected on: 03:11 PM 02 Dec, 2X
PID : 555 Ref. By: Dr. Hiren Shah Reported on: 04:35 PM 02 Dec, 2X
Complete Blood Count (CBC)
Investigation Result Reference Value Unit
Primary Sample Type : Blood
HEMOGLOBIN
Hemoglobin (Hb) 12.5 Low 13.0 - 17.0 g/dL
RBC COUNT
Total RBC count 5.2 4.5 - 5.5 mill/cumm
BLOOD INDICES
Packed Cell Volume (PCV) 57.5 High 40 - 50 %
Mean Corpuscular Volume (MCV) 87.75 83 - 101 fL
Calculated
MCH 27.2 27 - 32 pg
Calculated
MCHC 32.8 32.5 - 34.5 g/dL
Calculated
RDW 13.6 11.6 - 14.0 %
Smart Pathology Laboratory
WBC COUNT
Total WBC count 9000 4000-11000 cumm
DIFFERENTIAL WBC COUNT
Drlogy.com
Neutrophils 60 50 - 62 %
Lymphocytes 31 20 - 40 %
Eosinophils 1 00 - 06 %
Monocytes 7 00 - 10 %
Basophils 1 00 - 02 %
PLATELET COUNT
Platelet Count 150000 Borderline 150000 - 410000 cumm
Instruments: Fully automated cell counter - Mindray 300
Interpretation: Further confirm for Anemia
Thanks for Reference ****End of Report****
Medical Lab Technician Dr. Payal Shah Dr. Vimal Shah
(DMLT, BMLT) (MD, Pathologist) (MD, Pathologist)
Generated on : 02 Dec, 202X 05:00 PM Page 1 of 1
Sample Collection 0123456789



===== FILE: Hospital_Sample_Blood_Report.pdf =====


--- Page 1 (text) ---
SUNRISE MULTISPECIALITY HOSPITAL &
DIAGNOSTICS
Department of Pathology - Consolidated Blood Test Report
Report ID: SRH-2025-0915 Date: 27 Sept 2025
Prepared By: AI Diagnostic System Reviewed By: Dr. A. Sharma (MD Pathology)
Patient ID Age Gender Hemoglobin Ref RBC Ref WBC Ref Glucose Ref Cholesterol Ref
P001 24 M 14.2 13.5-17.5 5.1 4.2-

In [23]:
import re
cleaned_text = all_text.lower()
cleaned_text = cleaned_text.replace("\t", " ")
cleaned_text = re.sub(r"\s+", " ", cleaned_text)

print(cleaned_text[:1000])
print("\nTotal characters after cleaning:", len(cleaned_text))

 ===== file: cbc-test-report-format-example-sample-template-drlogy-lab-report.pdf ===== --- page 1 (text) --- drlogy pathology lab 0123456789 | 0912345678 drlogypathlab@drlogy.com accurate | caring | instant 105 -108, smart vision complex, healthcare road, opposite healthcare complex. mumbai - 689578 www.drlogy.com yash m. patel sample collected at: age : 21 years 125, shivam bungalow, s g road, registered on: 02:31 pm 02 dec, 2x mumbai sex : male collected on: 03:11 pm 02 dec, 2x pid : 555 ref. by: dr. hiren shah reported on: 04:35 pm 02 dec, 2x complete blood count (cbc) investigation result reference value unit primary sample type : blood hemoglobin hemoglobin (hb) 12.5 low 13.0 - 17.0 g/dl rbc count total rbc count 5.2 4.5 - 5.5 mill/cumm blood indices packed cell volume (pcv) 57.5 high 40 - 50 % mean corpuscular volume (mcv) 87.75 83 - 101 fl calculated mch 27.2 27 - 32 pg calculated mchc 32.8 32.5 - 34.5 g/dl calculated rdw 13.6 11.6 - 14.0 % smart pathology laboratory wbc count

Total characters after cleaning: 230781

In [24]:
with open("combined_raw_text.txt", "w", encoding="utf-8") as f:
    f.write(all_text)

with open("combined_cleaned_text.txt", "w", encoding="utf-8") as f:
    f.write(cleaned_text)

print("Saved combined_raw_text.txt and combined_cleaned_text.txt")

Saved combined_raw_text.txt and combined_cleaned_text.txt

In [25]:
from google.colab import files
files.download("combined_cleaned_text.txt")

In [26]:
import re

parameters = {
    "hemoglobin": r"hemoglobin[^0-9]*([0-9.]+)",
    "rbc": r"rbc[^0-9]*([0-9.]+)",
    "wbc": r"wbc[^0-9]*([0-9,]+)",
    "platelets": r"platelet[^0-9]*([0-9,]+)",
    "glucose": r"glucose[^0-9]*([0-9.]+)",
    "cholesterol": r"cholesterol[^0-9]*([0-9.]+)"
}

extracted_values = {}

for param, pattern in parameters.items():
    matches = re.findall(pattern, cleaned_text)
    extracted_values[param] = matches[:10]  # show first 10 found

extracted_values

{'hemoglobin': ['12.5', '001', '001', '14.5', '1', '1995', '2', '1'],
 'rbc': ['5.2', '001', '001', '4.79', '7'],
 'wbc': ['9000', '60', '001', '001', '10570', '7'],
 'platelets': ['150000', '001', '150000', '7'],
 'glucose': ['001', '001', '157.07', '1', '1', '1', '1.', '1', '40', '100'],
 'cholesterol': ['001',
  '001',
  '189.0',
  '200',
  '60.0',
  '2',
  '1',
  '2019',
  '64191',
  '2018']}

In [27]:
import pandas as pd

df = pd.DataFrame(dict([(k, pd.Series(v)) for k, v in extracted_values.items()]))
df

  hemoglobin   rbc    wbc platelets glucose cholesterol
0       12.5   5.2   9000    150000     001         001
1        001   001     60       001     001         001
2        001   001    001    150000  157.07       189.0
3       14.5  4.79    001         7       1         200
4          1     7  10570       NaN       1        60.0
5       1995   NaN      7       NaN       1           2
6          2   NaN    NaN       NaN      1.           1
7          1   NaN    NaN       NaN       1        2019
8        NaN   NaN    NaN       NaN      40       64191
9        NaN   NaN    NaN       NaN     100        2018

In [28]:
df.to_csv("extracted_parameters.csv", index=False)

from google.colab import files
files.download("extracted_parameters.csv")

In [34]:
import pandas as pd

df = pd.read_csv("extracted_parameters.csv")
print("Original data:")
print(df.head())

for col in df.columns:
    df[col] = df[col].astype(str).str.replace(",", "").str.strip()
    df[col] = pd.to_numeric(df[col], errors="coerce")

print("\nAfter basic cleaning (numeric conversion):")
print(df.head())

valid_ranges = {
    "hemoglobin": (5, 20),          # g/dL
    "rbc":        (2, 8),           # million cells/mcL
    "wbc":        (2000, 30000),    # cells/mcL
    "platelets":  (50000, 1000000), # platelets/mcL
    "glucose":    (40, 400),        # mg/dL
    "cholesterol":(50, 400)         # mg/dL
}

def classify_value(value, low, high):
    """Return a simple label for the value based on the range."""
    if pd.isna(value):
        return "missing"
    if value < low:
        return "low"
    if value > high:
        return "high"
    return "normal"

for col, (low, high) in valid_ranges.items():
    if col in df.columns:
        status_col = col + "_status"
        df[status_col] = df[col].apply(lambda v: classify_value(v, low, high))

print("\nWith status columns added:")
print(df.head())

main_params = [c for c in valid_ranges.keys() if c in df.columns]
df["non_missing_params"] = df[main_params].notna().sum(axis=1)
df_clean = df[df["non_missing_params"] > 0].drop(columns=["non_missing_params"])

print("\nCleaned and filtered data:")
print(df_clean.head())
df_clean.to_csv("validated_standardized_parameters.csv", index=False)
print("\nSaved validated_standardized_parameters.csv")
files.download("validated_standardized_parameters.csv")

Original data:
   hemoglobin   rbc      wbc  platelets  glucose  cholesterol
0        12.5  5.20   9000.0   150000.0     1.00          1.0
1         1.0  1.00     60.0        1.0     1.00          1.0
2         1.0  1.00      1.0   150000.0   157.07        189.0
3        14.5  4.79      1.0        7.0     1.00        200.0
4         1.0  7.00  10570.0        NaN     1.00         60.0

After basic cleaning (numeric conversion):
   hemoglobin   rbc      wbc  platelets  glucose  cholesterol
0        12.5  5.20   9000.0   150000.0     1.00          1.0
1         1.0  1.00     60.0        1.0     1.00          1.0
2         1.0  1.00      1.0   150000.0   157.07        189.0
3        14.5  4.79      1.0        7.0     1.00        200.0
4         1.0  7.00  10570.0        NaN     1.00         60.0

With status columns added:
   hemoglobin   rbc      wbc  platelets  glucose  cholesterol  \
0        12.5  5.20   9000.0   150000.0     1.00          1.0
1         1.0  1.00     60.0        1.0     1.00          1.0
2         1.0  1.00      1.0   150000.0   157.07        189.0
3        14.5  4.79      1.0        7.0     1.00        200.0
4         1.0  7.00  10570.0        NaN     1.00         60.0

  hemoglobin_status rbc_status wbc_status platelets_status glucose_status  \
0            normal     normal     normal           normal            low
1               low        low        low              low            low
2               low        low        low           normal         normal
3            normal     normal        low              low            low
4               low     normal     normal          missing            low

  cholesterol_status
0                low
1                low
2             normal
3             normal
4             normal

Cleaned and filtered data:
   hemoglobin   rbc      wbc  platelets  glucose  cholesterol  \
0        12.5  5.20   9000.0   150000.0     1.00          1.0
1         1.0  1.00     60.0        1.0     1.00          1.0
2         1.0  1.00      1.0   150000.0   157.07        189.0
3        14.5  4.79      1.0        7.0     1.00        200.0
4         1.0  7.00  10570.0        NaN     1.00         60.0

  hemoglobin_status rbc_status wbc_status platelets_status glucose_status  \
0            normal     normal     normal           normal            low
1               low        low        low              low            low
2               low        low        low           normal         normal
3            normal     normal        low              low            low
4               low     normal     normal          missing            low

  cholesterol_status
0                low
1                low
2             normal
3             normal
4             normal

Saved validated_standardized_parameters.csv

In [35]:
import pandas as pd

df = pd.read_csv("validated_standardized_parameters.csv")
df.head()

,hemoglobin,rbc,wbc,platelets,glucose,cholesterol,hemoglobin_status,rbc_status,wbc_status,platelets_status,glucose_status,cholesterol_status
0,12.5,5.20,9000.0,150000.0,1.00,1.0,normal,normal,normal,normal,low,low
1,1.0,1.00,60.0,1.0,1.00,1.0,low,low,low,low,low,low
2,1.0,1.00,1.0,150000.0,157.07,189.0,low,low,low,normal,normal,normal
3,14.5,4.79,1.0,7.0,1.00,200.0,normal,normal,low,low,low,normal
4,1.0,7.00,10570.0,NaN,1.00,60.0,low,normal,normal,missing,low,normal

In [36]:
def identify_patterns(row):
    insights = []

    # Anemia pattern
    if row.get("hemoglobin_status") == "low" and row.get("rbc_status") == "low":
        insights.append("possible_anemia_pattern")

    # High blood sugar pattern
    if row.get("glucose_status") == "high":
        insights.append("elevated_glucose_pattern")

    # Cholesterol risk pattern
    if row.get("cholesterol_status") == "high":
        insights.append("elevated_cholesterol_pattern")

    # Infection / inflammation pattern
    if row.get("wbc_status") == "high":
        insights.append("possible_infection_pattern")

    if not insights:
        insights.append("no_significant_pattern")

    return ", ".join(insights)

In [37]:
df["identified_patterns"] = df.apply(identify_patterns, axis=1)
df[["identified_patterns"]].head()

       identified_patterns
0   no_significant_pattern
1  possible_anemia_pattern
2  possible_anemia_pattern
3   no_significant_pattern
4   no_significant_pattern

In [38]:
df.to_csv("milestone2_pattern_analysis.csv", index=False)
print("Saved milestone2_pattern_analysis.csv")
files.download("milestone2_pattern_analysis.csv")

Saved milestone2_pattern_analysis.csv